name: legacy-lego-prod

networks:
  legacy-lego-network-prod:
    driver: bridge

volumes:
  postgres-legacy-lego-data:
    name: legacy-lego-prod-postgres-data
  seq-legacy-lego-data:
    name: legacy-lego-prod-seq-data
  redis-legacy-lego-data:
    name: legacy-lego-prod-redis-data
  nginx-legacy-lego-logs:
    name: legacy-lego-prod-nginx-logs
  goaccess-html:
    name: legacy-lego-prod-goaccess-html

services:
  # LegacyLego Api
  legacy-lego-api:
    container_name: legacy-lego-prod-api
    build:
      context: .
      dockerfile: Presentation.Dockerfile
      network: host
    env_file:
      - .env
    networks:
      - legacy-lego-network-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Database__ConnectionString=Host=legacy-lego-postgres;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER}
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}
      - Keycloak__PrivateApiClientId=${KEYCLOAK_API_CLIENT_ID}
      - Keycloak__PrivateApiClientSecret=${KEYCLOAK_API_CLIENT_SECRET}
      - RedisConnectionString=legacy-lego-redis:6379
      - PaymentProviderOptions__ApiBaseUrl=http://localhost:80/
    expose:
      - "8080"
    depends_on:
      legacy-lego-migrator:
        condition: service_completed_successfully
      legacy-lego-redis:
        condition: service_healthy
    restart: unless-stopped

  # Nginx
  legacy-lego-nginx:
    container_name: legacy-lego-prod-nginx
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    networks:
      - legacy-lego-network-prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/static:/usr/share/nginx/static:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - nginx-legacy-lego-logs:/var/log/nginx
      - goaccess-html:/var/www/goaccess:ro
    depends_on:
      legacy-lego-api:
        condition: service_started
    restart: unless-stopped

  # Мигратор БД
  legacy-lego-migrator:
    container_name: legacy-lego-prod-migrator
    build:
      context: .
      dockerfile: Presentation.Dockerfile
      target: migrator
      network: host
    env_file:
      - .env
    networks:
      - legacy-lego-network-prod
    command: [ "--connection", "Host=legacy-lego-postgres;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}" ]
    depends_on:
      legacy-lego-postgres:
        condition: service_healthy

  # СУБД PostgreSQL
  legacy-lego-postgres:
    container_name: legacy-lego-prod-postgres
    image: postgres:16-alpine
    env_file:
      - .env
    networks:
      - legacy-lego-network-prod
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - postgres-legacy-lego-data:/var/lib/postgresql/data

  # Redis (Распределённое кэширование)
  legacy-lego-redis:
    container_name: legacy-lego-prod-redis
    image: redis:7-alpine
    networks:
      - legacy-lego-network-prod
    volumes:
      - redis-legacy-lego-data:/data
    expose:
      - "6379"
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  # Redis Commander (Монитор кэша)
  legacy-lego-redis-commander:
    container_name: legacy-lego-prod-redis-commander
    image: rediscommander/redis-commander:snyk-fix-1841981ea4b1abcbc4c13e21d5d2997d
    environment:
      - REDIS_HOSTS=local:legacy-lego-redis:6379
      #  - HTTP_USER=${REDIS_COMMANDER_USER}
      #  - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD}
      - URL_PREFIX=/redcomm
    expose:
      - "8081"
    networks:
      - legacy-lego-network-prod
    restart: unless-stopped

  # Seq (Логирование)
  legacy-lego-seq:
    container_name: legacy-lego-prod-seq
    image: datalust/seq:2025.2
    env_file:
      - .env
    networks:
      - legacy-lego-network-prod
    environment:
      - ACCEPT_EULA=Y
      - SEQ_PASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    expose:
      - "5341"
      - "80"
    volumes:
      - seq-legacy-lego-data:/data
    restart: unless-stopped

  # Goaccess (логгирование сетевых обращений Nginx)
  legacy-lego-goaccess:
    container_name: legacy-lego-prod-goaccess
    image: allinurl/goaccess
    networks:
      - legacy-lego-network-prod
    expose:
      - "7890"
    volumes:
      - nginx-legacy-lego-logs:/var/log/nginx:ro
      - goaccess-html:/var/www/goaccess
    entrypoint: /bin/sh -c
    command:
      - >
        while true; do
          goaccess /var/log/nginx/access-api.log --log-format=COMBINED -o /var/www/goaccess/index.html;
          sleep 10;
        done
    # command:
    #  - >
    #   goaccess /var/log/nginx/access-api.log
    #   --log-format=COMBINED
    #   --real-time-html
    #   -o /var/www/goaccess/index.html
    #   --port=7890
    #   --ws-url=ws://localhost:7890
    restart: unless-stopped

  # Homepage Infrastructure Dashboard (Local-Prod)
  legacy-lego-dashboard:
    container_name: legacy-lego-prod-dashboard
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=localhost:8090,localhost,127.0.0.1:8090,127.0.0.1
      #- HOMEPAGE_ALLOWED_HOSTS=localhost,localhost:8080,127.0.0.1,legacy-lego-nginx
    ports:
      - "127.0.0.1:8090:3000" # доступ только с текущего устройства
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infrastructure/dashboard/local-prod:/app/config
      - ./infrastructure/dashboard/shared/images:/app/public/icons
      - ./infrastructure/dashboard/local-prod/public/credentials.html:/app/public/credentials.html
      - ./infrastructure/dashboard/local-prod/public/credentials.js:/app/public/credentials.js
      - ./infrastructure/dashboard/local-prod/public/credentials.js.example:/app/public/credentials.js.example
    networks:
      - legacy-lego-network-prod
    restart: unless-stopped

  # Keycloak (OAuth 2.0 & OIDC Identity Provider)
  legacy-lego-keycloak:
    image: keycloak/keycloak:26.7
    container_name: legacy-lego-prod-keycloak
    env_file:
      - .env
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

      # 1. Говорим Keycloak, что он работает на подмаршруте /auth
      - KC_HTTP_RELATIVE_PATH=/auth

      # 2. Указываем, что перед нами Nginx, передающий X-Forwarded-* заголовки
      - KC_PROXY_HEADERS=xforwarded

      # 3. Базовый публичный URL (то, что будет зашиваться в 'iss' токена)
      - KC_HOSTNAME_URL=http://localhost/auth
      - KC_HOSTNAME_STRICT=false

      # Конфигурация подключения плагина к RabbitMQ
      - KK_TO_RMQ_URL=legacy-lego-rabbitmq
      - KK_TO_RMQ_PORT=5672
      - KK_TO_RMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - KK_TO_RMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - KK_TO_RMQ_VHOST=/
      - KK_TO_RMQ_EXCHANGE=amq.topic
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./infrastructure/keycloak/realm-config-local-prod.json:/opt/keycloak/data/import/realm-config.json:ro
      - ./infrastructure/keycloak/plugins/keycloak-to-rabbit-3.0.5.jar:/opt/keycloak/providers/keycloak-to-rabbitmq.jar
    expose:
      - "8080"
      - "9000"
    networks:
      - legacy-lego-network-prod
    command: [ "start-dev", "--import-realm" ]
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/9000 && echo -e \"GET /auth/health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n\" >&3 && cat <&3 | grep -q \"UP\"' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    depends_on:
      legacy-lego-rabbitmq:
        condition: service_healthy

  # RabbitMQ (Брокер сообщений)
  legacy-lego-rabbitmq:
    container_name: legacy-lego-prod-rabbitmq
    image: rabbitmq:3-management-alpine
    networks:
      - legacy-lego-network-prod
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./infrastructure/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    expose:
      - "5672"
      - "15672" # Management UI
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
