volumes:
  postgres-legacy-lego-data:
  seq-legacy-lego-data:
  redis-legacy-lego-data:
  hompage-dashboard-config-data:

networks:
  legacy-lego-network:
    driver: bridge

services:
  legacy-lego-postgres:
    image: postgres:16-alpine
    container_name: legacy-lego-postgres
    env_file:
      - .env
    networks:
      - legacy-lego-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - postgres-legacy-lego-data:/var/lib/postgresql/data
  legacy-lego-seq:
    image: datalust/seq:2025.2
    container_name: legacy-lego-seq
    env_file:
      - .env
    networks:
      - legacy-lego-network
    environment:
      - ACCEPT_EULA=Y
      - SEQ_PASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    ports:
      - "8081:80"
      - "5341:5341"
    volumes:
      - seq-legacy-lego-data:/data
    restart: unless-stopped
  legacy-lego-redis:
    image: redis:7-alpine
    container_name: legacy-lego-redis
    networks:
      - legacy-lego-network
    ports:
      - "6379:6379"
    volumes:
      - redis-legacy-lego-data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
  legacy-lego-redis-commander:
    image: rediscommander/redis-commander:snyk-fix-1841981ea4b1abcbc4c13e21d5d2997d
    container_name: legacy-lego-redis-commander
    environment:
      - REDIS_HOSTS=local:legacy-lego-redis:6379
      - HTTP_USER=${REDIS_COMMANDER_USER}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD}
    ports:
      - "8082:8081"
    networks:
      - legacy-lego-network
    restart: unless-stopped
  legacy-lego-dashboard:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: legacy-lego-dashboard
    ports:
      - "8090:3000"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=localhost:8090,localhost,127.0.0.1:8090,127.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway" # Позволяет контейнеру стучаться на хост-машину
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Для чтения статусов контейнеров
      - ./infrastructure/dashboard/dev:/app/config
      - ./infrastructure/dashboard/shared/images:/app/public/icons
      - ./infrastructure/dashboard/dev/public/credentials.html:/app/public/credentials.html
      - ./infrastructure/dashboard/dev/public/credentials.js:/app/public/credentials.js
      - ./infrastructure/dashboard/dev/public/credentials.js.example:/app/public/credentials.js.example
    networks:
      - legacy-lego-network
    restart: unless-stopped

  legacy-lego-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: legacy-lego-rabbitmq
    ports:
      - "5672:5672" # AMQP порт (для подключения .NET и Keycloak)
      - "15672:15672" # Web UI Management Dashboard
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    volumes:
      - ./infrastructure/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  legacy-lego-keycloak:
    image: keycloak/keycloak:26.7
    container_name: legacy-lego-keycloak
    env_file:
      - .env
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      # Конфигурация подключения плагина к RabbitMQ
      - KK_TO_RMQ_URL=legacy-lego-rabbitmq
      - KK_TO_RMQ_PORT=5672
      - KK_TO_RMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - KK_TO_RMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - KK_TO_RMQ_VHOST=/
      - KK_TO_RMQ_EXCHANGE=amq.topic
    volumes:
      - ./infrastructure/keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json:ro
      - ./infrastructure/keycloak/plugins/keycloak-to-rabbit-3.0.5.jar:/opt/keycloak/providers/keycloak-to-rabbitmq.jar
    ports:
      - 8084:8080
      - 9000:9000 # exposed healthcheck
    command: [ "start-dev", "--import-realm" ]
    restart: unless-stopped
    depends_on:
      legacy-lego-rabbitmq:
        condition: service_healthy
