volumes:
 postgres-legacy-lego-data:
  name: legacy-lego-prod-postgres-data
 seq-legacy-lego-data:
  name: legacy-lego-prod-seq-data
 redis-legacy-lego-data:
  name: legacy-lego-prod-redis-data
 nginx-legacy-lego-logs:
  name: legacy-lego-prod-nginx-logs
 goaccess-html:
  name: legacy-lego-prod-goaccess-html

name: legacy-lego-prod

networks:
 legacy-lego-network-prod:
  driver: bridge

services:
# LegacyLego Api
 legacy-lego-api:
  build:
   context: .
   dockerfile: Presentation.Dockerfile
  env_file:
   - .env
  networks:
   - legacy-lego-network-prod
  environment:
   - ASPNETCORE_ENVIRONMENT=Production
   - Database__ConnectionString=Host=legacy-lego-postgres;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
   - RedisConnectionString=legacy-lego-redis:6379
   - Serilog__WriteTo__0__Args__serverUrl=http://legacy-lego-seq:5341
  expose:
   - "8080"
  depends_on:
   legacy-lego-migrator:
    condition: service_completed_successfully
   legacy-lego-redis:
    condition: service_healthy
  restart: unless-stopped
 # Nginx
 legacy-lego-nginx:
  image: nginx:1.27-alpine
  ports:
   - "80:80"
  networks:
   - legacy-lego-network-prod
  volumes:
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
   - ./nginx/static:/usr/share/nginx/static:ro
   - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
   - nginx-legacy-lego-logs:/var/log/nginx
   - goaccess-html:/var/www/goaccess:ro
  depends_on:
   legacy-lego-api:
    condition: service_started
  restart: unless-stopped
  # 3. Мигратор БД
 legacy-lego-migrator:
  build:
   context: .
   dockerfile: Presentation.Dockerfile
   target: migrator
  env_file:
   - .env
  networks:
   - legacy-lego-network-prod
  command: ["--connection", "Host=legacy-lego-postgres;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"]
  depends_on:
   legacy-lego-postgres:
    condition: service_healthy

 # 4. СУБД PostgreSQL
 legacy-lego-postgres:
  image: postgres:16-alpine
  env_file:
   - .env
  networks:
   - legacy-lego-network-prod
  environment: 
   - POSTGRES_PASSWORD=${DB_PASSWORD}
   - POSTGRES_USER=${DB_USER}
   - POSTGRES_DB=${DB_NAME}
  healthcheck:
   test: ["CMD-SHELL","pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
   interval: 5s
   timeout: 5s
   retries: 3
  restart: unless-stopped
  volumes:
   - postgres-legacy-lego-data:/var/lib/postgresql/data

  # Redis (Распределённое кэширование)
 legacy-lego-redis: 
  image: redis:7-alpine 
  networks:
   - legacy-lego-network-prod
  volumes:
   - redis-legacy-lego-data:/data
  expose:
   - "6379"
  command: redis-server --save 60 1 --loglevel warning
  healthcheck:
   test: ["CMD", "redis-cli", "ping"]
   interval: 5s
   timeout: 3s
   retries: 3
  restart: unless-stopped

 # Seq (Логирование)
 legacy-lego-seq:
  image: datalust/seq:2025.2
  env_file:
   - .env
  networks:
   - legacy-lego-network-prod
  environment:
   - ACCEPT_EULA=Y
   - SEQ_PASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
  expose:
   - "5341"
   - "80"
  volumes:
   - seq-legacy-lego-data:/data
  restart: unless-stopped
  # Goaccess (логгирование сетевых обращений Nginx)
 legacy-lego-goaccess:
  image: allinurl/goaccess
  networks:
   - legacy-lego-network-prod
  expose:
   - "7890"
  volumes:
   - nginx-legacy-lego-logs:/var/log/nginx:ro
   - goaccess-html:/var/www/goaccess
  entrypoint: /bin/sh -c
  command:
   - >
    while true; do
        goaccess /var/log/nginx/access-api.log --log-format=COMBINED -o /var/www/goaccess/index.html;
        sleep 10;
      done
  # command:
  #  - >
  #   goaccess /var/log/nginx/access-api.log
  #   --log-format=COMBINED
  #   --real-time-html
  #   -o /var/www/goaccess/index.html
  #   --port=7890
  #   --ws-url=ws://localhost:7890
  restart: unless-stopped