// <auto-generated />
using System;
using System.Collections.Generic;
using LegacyLego.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LegacyLego.Infrastructure.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20260803143309_AddOrderPaymentActualAndExpectedPriceAmounts")]
    partial class AddOrderPaymentActualAndExpectedPriceAmounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LegacyLego.Domain.Aggregates.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreationDateUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<decimal?>("FrozenTotalSum")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("frozen_total_sum");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "LegacyLego.Domain.Aggregates.Order.Address#OrderAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("address_street");
                        });

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.ToTable("Order", null, t =>
                        {
                            t.HasCheckConstraint("check_order_frozen_total_sun", "\"frozen_total_sum\" >= 0");

                            t.HasCheckConstraint("check_order_status", "\"status\" IN ('PendingPayment', 'Paid', 'Cancelled', 'Expired', 'Refunded')");
                        });
                });

            modelBuilder.Entity("LegacyLego.Domain.Aggregates.OrderPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("transaction_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ActualAmount", "LegacyLego.Domain.Aggregates.OrderPayment.ActualAmount#Price", b1 =>
                        {
                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("actual_currency");

                            b1.Property<decimal>("Sum")
                                .HasPrecision(15, 2)
                                .HasColumnType("numeric(15,2)")
                                .HasColumnName("actual_amount");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ExpectedAmount", "LegacyLego.Domain.Aggregates.OrderPayment.ExpectedAmount#Price", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("expected_currency");

                            b1.Property<decimal>("Sum")
                                .HasColumnType("numeric(15,2)")
                                .HasColumnName("expected_amount");
                        });

                    b.HasKey("Id")
                        .HasName("pk_order_payment");

                    b.HasIndex("OrderId");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("transaction_id IS NOT NULL");

                    b.ToTable("Order_payment", null, t =>
                        {
                            t.HasCheckConstraint("check_order_payment_status", "\"status\" IN ('Pending', 'Succeeded', 'Failed', 'Refunded', 'RefundRequested')");
                        });
                });

            modelBuilder.Entity("LegacyLego.Domain.ValueObjects.ExternalSession", b =>
                {
                    b.Property<Guid>("OrderPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_payment_id");

                    b.Property<string>("CheckoutUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checkout_url");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("external_id");

                    b.HasKey("OrderPaymentId")
                        .HasName("pk_external_session");

                    b.ToTable("External_session", (string)null);
                });

            modelBuilder.Entity("LegacyLego.Domain.ValueObjects.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "LegacyLego.Domain.ValueObjects.OrderItem.UnitPrice#Price", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("currency_code");

                            b1.Property<decimal>("Sum")
                                .HasColumnType("numeric(15,2)")
                                .HasColumnName("unit_price");
                        });

                    b.HasKey("Id")
                        .HasName("pk_order_item");

                    b.HasIndex("OrderId");

                    b.ToTable("Order_item", null, t =>
                        {
                            t.HasCheckConstraint("check_quantity", "\"quantity\" >= 1");

                            t.HasCheckConstraint("check_unit_price_status", "\"unit_price\" > 0");
                        });
                });

            modelBuilder.Entity("LegacyLego.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("Outbox_messages", (string)null);
                });

            modelBuilder.Entity("LegacyLego.Domain.Aggregates.OrderPayment", b =>
                {
                    b.HasOne("LegacyLego.Domain.Aggregates.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_payment_orders");
                });

            modelBuilder.Entity("LegacyLego.Domain.ValueObjects.ExternalSession", b =>
                {
                    b.HasOne("LegacyLego.Domain.Aggregates.OrderPayment", null)
                        .WithOne("ExternalSession")
                        .HasForeignKey("LegacyLego.Domain.ValueObjects.ExternalSession", "OrderPaymentId");
                });

            modelBuilder.Entity("LegacyLego.Domain.ValueObjects.OrderItem", b =>
                {
                    b.HasOne("LegacyLego.Domain.Aggregates.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_order_items");
                });

            modelBuilder.Entity("LegacyLego.Domain.Aggregates.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LegacyLego.Domain.Aggregates.OrderPayment", b =>
                {
                    b.Navigation("ExternalSession");
                });
#pragma warning restore 612, 618
        }
    }
}
