<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LegacyLego.Domain\LegacyLego.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Orders\Commands\Cancel\" />
    <Folder Include="Orders\Commands\Refund\" />
  </ItemGroup>

</Project>
